# Generated by Django 4.0.3 on 2022-03-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klientai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klientai',
            new_name='Klientas',
        ),
    ]
